### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by makermelissa** [Nicolai-Electronics/rp2040-i2c-interface#2]
I wanted to try this on some other boards, but I have been unable to get it to compile. I'm not sure if it's:
1. An issue with the make file
2. The lack of instructions causing me to do it wrong

Here's what I've been trying.
1. I clone the repo
2. I run `export PICO_SDK_PATH=(pwd)` from inside my pico-sdk directory
3. In the cloned repo, I make a build folder
4. inside the build folder I run `cmake .. -DPICO_BOARD=adafruit_trinkey_qt2040`
5. I then run make and get `error: #error multiple boot stage 2 options chosen`

**Comment by CorvetteCole** [comment]
I have this working properly with the Adafruit Trinkey QT2040 now. I used the default build files and changed lines 25-27 in main.c from
```C
#define I2C_INST i2c1
#define I2C_SDA  2
#define I2C_SCL  3
```


to
```C
#define I2C_INST i2c0
#define I2C_SDA  16
#define I2C_SCL  17
```

**Comment by renzenicolai** [comment]
Compiles fine for me using the latest SDK, if this problem still exists for you please open a new ticket with some more details like a full listing of the output of the make command.
