### ISSUE TITLE
Bus idles with SCL low / missing stop codes

### ISSUE THREAD

**Issue by jnelgh** [Nicolai-Electronics/rp2040-i2c-interface#3]
I'm using the pre-build .ucf on a pico as an I2C interface for my Ubuntu PC. Running some C code (ioctl, i2c-dev) to read/write an EEPROM chip I had issues with writing; with a logic analyzer I found that when idle SCL is low instead of high and (maybe as a result) I see no valid stop codes at the end of a transaction (SDA rising while SCL is high).
I ran the same code on a raspberry pi on it's internal I2C bus and there SCL is low between transactions and every transaction ends with a stop.

![i2c_pico_nostop](https://user-images.githubusercontent.com/68012349/211782897-cd2c9ea5-f0f8-4c86-a88e-8b5f061cfe51.png)
In this view, start codes are marked by a green dot, stop codes by a red dot (and there are no red dots here).
For I2C reads this does not appear to be an issue but for writing an EEPROM it is since these chips (24FC256 and the like) will not execute writes if the transaction is not finalized with a valid stop.
Also leaving SCL high when idle gives some opportunity for multi-master use of the bus.

Besides this, thank you for the project, it's a good use of picos and a nice way to use I2C on PC instead of rpi.

**Comment by jnelgh** [comment]
Actually in main.c line 148 you're calling a write routine with as last argument 'stop'. In the pico sdk I only find a write routine that has as final argument 'bool nostop'. Could it be that this needs to be inverted?
I'm unable to compile the code myself at the moment unfortunately (environment messed up) so I cannot test it.

**Comment by jnelgh** [comment]
FYI I managed to hack around the problem, by forcing stop to false (main.c line 116, unconditional). I can now read and write I2C EEPROMs succesfully but there is some spurious activity on the bus, it's not a clean solution. I did not manage to work this up to a proper fix but at least I can use it for my purpose now.

**Comment by ewpa** [comment]
Confirming the same behavior on the RP2 but not on the ATTINY85.    I had started investigating and saw your logged issue.  Try negating `stop` rather than setting to `false`.  You already noticed the final parameter to `i2c_read_blocking` and `i2c_write_blocking` is `nostop` rather than `stop`.  The negation addresses this I believe, but needs more testing.
